### ISSUE TITLE
Failing to resolve dependencies

### ISSUE THREAD

**Issue by BitlyTwiser** [timkendall/crynamo#25]
Attempting a `shards install` after adding in the crynamo dependency fails due to the inability to resolve dependencies. 

Error: 
```Unable to satisfy the following requirements:

- crynamo (~> 0.1.1) required by shard.yml
Failed to resolve dependencies
```

Dependencies:
```
dependencies:
  db:
    github: crystal-lang/crystal-db
  pg:
    github: will/crystal-pg
  dotenv:
    github: xtokio/dotenv
  logger:
    github: crystal-lang/logger.cr
  crynamo:
    github: timkendall/crynamo
    version: ~> 0.1.1
```

Crystal version:
```
Crystal 1.2.2 (2021-11-10)

LLVM: 11.1.0
Default target: x86_64-apple-macosx
```
